import Link from "next/link";

export const metadata = {
  title: "Terms of Service — MirrorQuiz",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <Link
        href="/"
        className="text-sm text-muted-foreground hover:text-foreground"
      >
        &larr; Back to Home
      </Link>

      <h1 className="mt-6 text-3xl font-bold">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated: February 2026
      </p>

      <div className="mt-8 space-y-6 text-muted-foreground leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold text-foreground">
            Acceptance of Terms
          </h2>
          <p>
            By accessing or using MirrorQuiz (&ldquo;the Service&rdquo;), you agree to
            be bound by these Terms of Service. If you do not agree, do not use
            the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            Description of Service
          </h2>
          <p>
            MirrorQuiz is a personality comparison tool that allows you to
            rate yourself on personality traits and invite others to rate you
            anonymously. Results are generated by comparing self-ratings with
            friend ratings.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            User Accounts
          </h2>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>
              You must provide a valid email address to create a quiz.
            </li>
            <li>
              You are responsible for maintaining the security of your account.
            </li>
            <li>
              Friend respondents do not need an account. Their responses are
              anonymous.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            Acceptable Use
          </h2>
          <p>You agree not to:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Use the Service to harass, bully, or harm others.</li>
            <li>
              Submit false or misleading information with malicious intent.
            </li>
            <li>
              Attempt to access another user&apos;s account or data without
              authorization.
            </li>
            <li>
              Use automated tools to scrape or abuse the Service.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            Payments &amp; Refunds
          </h2>
          <p>
            The basic quiz is free. Detailed reports are available as a one-time
            purchase. All payments are processed securely through Stripe. Because
            digital reports are delivered instantly, all sales are final. If you
            experience a technical issue preventing access to a purchased report,
            contact us for assistance.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            Intellectual Property
          </h2>
          <p>
            The Service, including its design, code, and content, is owned by
            MirrorQuiz. Your quiz responses and results belong to you. By
            using the Service, you grant us a limited license to process your
            data solely to provide the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            Disclaimer
          </h2>
          <p>
            MirrorQuiz is an entertainment and self-reflection tool, not a
            clinical psychological assessment. Results should not be used as a
            substitute for professional advice. The Service is provided &ldquo;as
            is&rdquo; without warranties of any kind.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            Limitation of Liability
          </h2>
          <p>
            To the maximum extent permitted by law, MirrorQuiz shall not be
            liable for any indirect, incidental, or consequential damages arising
            from your use of the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            Termination
          </h2>
          <p>
            We may suspend or terminate your access to the Service at any time
            for violation of these Terms. You may delete your account at any time
            by contacting{" "}
            <a
              href="mailto:support@mirrorquiz.com"
              className="text-primary hover:underline"
            >
              support@mirrorquiz.com
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            Changes to Terms
          </h2>
          <p>
            We may update these Terms from time to time. Continued use of the
            Service after changes constitutes acceptance of the updated Terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">Contact</h2>
          <p>
            Questions about these terms? Email{" "}
            <a
              href="mailto:support@mirrorquiz.com"
              className="text-primary hover:underline"
            >
              support@mirrorquiz.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
